spring.application.name=${APP_NAME:store}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/store}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:validate}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SHOW_SQL:true}

scalar.theme=${SCALAR_THEME:deepSpace}
scalar.layout=modern
scalar.documentDownloadType=both
scalar.path=/docs
scalar.enabled=${SCALAR_ENABLED:true}
scalar.url=/v3/api-docs

springdoc.packages-to-scan=com.aldian.store.controller