spring.application.name=store

spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

scalar.theme=deepSpace
scalar.layout=modern
scalar.documentDownloadType=both
scalar.path=/docs
scalar.enabled=true
scalar.url=/v3/api-docs

springdoc.packages-to-scan=com.aldian.store.controller